version: "2"
linters:
  enable:
    - forcetypeassert
    - goconst
    - gocritic
    - godox
    - gosec
    - iface
    - intrange
    - musttag
    - nilnil
    - perfsprint
    - revive
    - sloglint
    - testifylint
    - thelper
    - tparallel
  settings:
    goconst:
      ignore-calls: true
    gocritic:
      enable-all: true
    iface:
      enable:
        - identical
        - unused
    nilnil:
      detect-opposite: true
      checked-types:
        - chan
        - func
        - iface
        - map
        - ptr
        - uintptr
        - unsafeptr
    revive:
      confidence: 0.1
      rules:
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
          severity: error
          disabled: false
          exclude:
            - ""
        - name: early-return
          arguments:
            - preserveScope
            - allowJump
          severity: error
          disabled: false
          exclude:
            - ""
        - name: enforce-map-style
          arguments:
            - make
          severity: error
          disabled: false
          exclude:
            - ""
        - name: enforce-slice-style
          arguments:
            - make
          severity: error
          disabled: false
          exclude:
            - ""
        - name: filename-format
          arguments:
            - ^[_a-z][_a-z0-9]*.go$
          severity: error
          disabled: false
          exclude:
            - ""
        - name: optimize-operands-order
          severity: error
          disabled: false
          exclude:
            - ""
    sloglint:
      attr-only: true
      static-msg: true
      no-raw-keys: true
      key-naming-case: snake
      forbidden-keys:
        - time
        - level
        - msg
        - source
        - foo
      args-on-sep-lines: true
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: (.+)_test.go
        text: ^(enforce-slice-style|enforce-map-style)
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
