// Code generated by mockery v2.46.2. DO NOT EDIT.

package patcher

import mock "github.com/stretchr/testify/mock"

// MockPatchOpt is an autogenerated mock type for the PatchOpt type
type MockPatchOpt struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockPatchOpt) Execute(_a0 *SQLPatch) {
	_m.Called(_a0)
}

// NewMockPatchOpt creates a new instance of MockPatchOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPatchOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPatchOpt {
	mock := &MockPatchOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
