// Code generated by mockery. DO NOT EDIT.

package patcher

import mock "github.com/stretchr/testify/mock"

// MockLoaderOption is an autogenerated mock type for the LoaderOption type
type MockLoaderOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockLoaderOption) Execute(_a0 *loader) {
	_m.Called(_a0)
}

// NewMockLoaderOption creates a new instance of MockLoaderOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoaderOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoaderOption {
	mock := &MockLoaderOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
