// Code generated by mockery. DO NOT EDIT.

package patcher

import mock "github.com/stretchr/testify/mock"

// MockMultiFilter is an autogenerated mock type for the MultiFilter type
type MockMultiFilter struct {
	mock.Mock
}

// Add provides a mock function with given fields: where
func (_m *MockMultiFilter) Add(where interface{}) {
	_m.Called(where)
}

// Join provides a mock function with no fields
func (_m *MockMultiFilter) Join() (string, []interface{}) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Join")
	}

	var r0 string
	var r1 []interface{}
	if rf, ok := ret.Get(0).(func() (string, []interface{})); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() []interface{}); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]interface{})
		}
	}

	return r0, r1
}

// Where provides a mock function with no fields
func (_m *MockMultiFilter) Where() (string, []interface{}) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Where")
	}

	var r0 string
	var r1 []interface{}
	if rf, ok := ret.Get(0).(func() (string, []interface{})); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() []interface{}); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]interface{})
		}
	}

	return r0, r1
}

// NewMockMultiFilter creates a new instance of MockMultiFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMultiFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMultiFilter {
	mock := &MockMultiFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
