// Code generated by mockery. DO NOT EDIT.

package patcher

import mock "github.com/stretchr/testify/mock"

// mockLoaderOption is an autogenerated mock type for the loaderOption type
type mockLoaderOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *mockLoaderOption) Execute(_a0 *loader) {
	_m.Called(_a0)
}

// newMockLoaderOption creates a new instance of mockLoaderOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLoaderOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLoaderOption {
	mock := &mockLoaderOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
