name: Bug Report
description: File a bug report
title: "Bug: "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide the following information to help us resolve the issue quickly.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the unexpected behavior you encountered.
      placeholder: Describe the unexpected behavior
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
      placeholder: Describe the expected behavior
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Provide detailed steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste any relevant log output. This will be automatically formatted into code.
      render: shell
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment (e.g., database type, Patcher version, etc.).
      placeholder: e.g., MySQL 8.0, Patcher v0.1.0
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any other context about the problem