name: Feature Request
description: Suggest a new feature or enhancement
title: "Feature: "
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please provide the following information to help us understand your suggestion.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please describe the feature you would like to see added.
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: feature-impact
    attributes:
      label: Feature Impact
      description: Please describe how you think this feature will impact the project.
      placeholder: I think this feature will impact the project by...
    validations:
      required: true
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide examples of how this feature would be used.
      placeholder: Example use cases for this feature...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternative solutions or features...
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any other context or screenshots about the feature request
