// Code generated by mockery. DO NOT EDIT.

package inserter

import mock "github.com/stretchr/testify/mock"

// MockBatchOpt is an autogenerated mock type for the BatchOpt type
type MockBatchOpt struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockBatchOpt) Execute(_a0 *SQLBatch) {
	_m.Called(_a0)
}

// NewMockBatchOpt creates a new instance of MockBatchOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchOpt {
	mock := &MockBatchOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
